# Generated by Django 3.1.5 on 2021-04-15 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_message',
            field=models.CharField(max_length=1280, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_message_date',
            field=models.DateTimeField(default=None, verbose_name=django.utils.timezone.now),
        ),
    ]
