# Generated by Django 3.1.5 on 2021-04-15 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0002_auto_20210415_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='last_message_date',
            field=models.DateTimeField(default=None, null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
