# Generated by Django 3.1.5 on 2021-05-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0003_auto_20210415_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
