# Generated by Django 3.1.5 on 2021-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0004_channel_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
