# Generated by Django 3.1.5 on 2021-05-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sockets', '0006_channel_connected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_message_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
