# Generated by Django 3.1.5 on 2021-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sockets', '0007_channel_last_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
