# Generated by Django 3.1.5 on 2021-03-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='User',
            new_name='user',
        ),
    ]
