# Generated by Django 3.1.5 on 2021-03-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_post_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='sub_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wall.postcomment'),
        ),
    ]
