# Generated by Django 3.1.5 on 2021-03-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0010_postcomment_sub_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='sub_comment',
            new_name='parent',
        ),
    ]
