# Generated by Django 3.1.5 on 2021-03-24 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0011_auto_20210323_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comments',
        ),
    ]
