# Generated by Django 3.1.5 on 2021-05-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0014_auto_20210329_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
