# Generated by Django 3.1.5 on 2021-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0015_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ratio',
            field=models.IntegerField(default=0),
        ),
    ]
